var fractal_param = {
  // 'disable_load': true,
  'start_state': {
    'phase': 'init',
    'init': {'phase': 'intro', 'intro': 0},
    'bought': {},
    'unlocked': {},
    'tick': 0,
    'click': 0,
    'cursor_clicks': 0,
    'cursor_clicks_per_tick': 0,
    'points': 0,
    'points_per_tick': 0,
    'pellets': 0,
    'pellet_loaded': 1,
    'garden_seed': 'pretty'
  },
  'init': {
    'intro': [100, 'make_mouth', {}],
    'make_mouth': [25, 'turn_mouth', {}],
    'turn_mouth': [100, 'move_text', {}],
    'move_text': [25, 'crush_text', {}],
    'crush_text': [100, 'open_mouth', {}],
    'open_mouth': [25, 'make_line1', {}],
    'make_line': [14*6, 'cut_line', {}],
    'make_line1': [8*10, 'cut_line', {}],
    'cut_line': [25, 'open_mouth2', {'line': 1, 'pellet_loaded': -1}],
    'open_mouth2': [25, 'idle', {}],
    'idle': [1, 'idle', {}],
    'unknown': 'unknown'
  },
  'achievements': {
    'auto_cursor_click': {
      'unlock': {'points': 10},
      'cost': {'points': 20},
      'benefit': {'cursor_clicks_per_tick': .10001},
      'title': 'Auto Cursor Click',
      'text': 'Save that finger.',
      'max_buy': 1,
      'display_message': 'With great relief, a snail emerges into the world.',
    },
    'buy_pellets': {
      'unlock': {'line': 1},
      'cost': {'line': 1},
      'benefit': {'pellets': 2, 'show_pellets': 1},
      'title': 'Buy Pellets',
      'text': 'Without resources nothing moves.',
      'max_buy': -1,
      'display_message': 'Tied to a never ending cycle...',
    },
    'auto_cursor_click_from_line': {
      'unlock': {'line': 'Math.ceil(Math.floor(2**((n-1)/2))/2)',
                 'pellet_loaded': 1},
      'cost': {'line': 'Math.floor(2**((n-1)/2))'},
      'benefit': {'cursor_clicks_per_tick': '0.1*2**Math.floor(n/2)'},
      'title': 'Faster Auto Click',
      'text': 'Decisions were made.',
      'max_buy': 10,
      'display_message': 'Faster, faster, faster.',
    },
    'auto_cursor_click_from_points': {
      'unlock': {'points': 'Math.ceil(100*Math.floor(2**((n-1)/2))/2)',
                 'cursor_clicks_per_tick': .01},
      'cost': {'points': '100*Math.floor(2**((n-1)/2))'},
      'benefit': {'cursor_clicks_per_tick': '(n+1)/10'},
      'title': 'Points for Clicks',
      'text': 'What are these good for anyway?',
      'max_buy': 19,
      'display_message': 'What is the value of a point, if not to acquire more points?',
    },
    'auto_cursor_click_from_pellets': {
      'unlock': {'pellets': 'Math.ceil(4*(2**Math.floor((n-1)/10))/2)',
                 'cursor_clicks_per_tick': 2},
      'cost': {'pellets': '4*(2**Math.floor((n-1)/10))'},
      'benefit': {'cursor_clicks_per_tick': 'n/10'},
      'title': 'Feed Pellets to the Clicker',
      'text': 'Try not to get your finger caught',
      'max_buy': 20,
      'display_message': 'Do these fit?',
    },
    'make_box': {
      'unlock': {'line': 2},
      'cost': {'line': 4},
      'benefit': {'box': 1, 'show_box': 'set:line'},
      'title': 'Make a box',
      'text': 'To put things in',
      'max_buy': 1,
      'display_message': 'It is the packaging that matters more than the contents.',
    },
    'plant_pellets': {
      'unlock': {'pellets': 3},
      'cost': {'pellets': 2},
      'benefit': {'garden': 1, 'garden_speed': 1},
      'title': 'Plant Pellets',
      'text': 'Perhaps a garden will grow.',
      'max_buy': 1,
      'display_message': 'What goes down must come up.',
    },
    'garden_speed': {
      'unlock': {'pellets': '(4**n)/2', 'garden': 1},
      'cost': {'pellets': '4**n'},
      'benefit': {'garden_speed': 1},
      'title': 'Encourage the Plants',
      'text': 'Presumably they enjoy it.',
      'max_buy': 2,
      'display_message': 'You\'re pretty sure this is working.',
    },
    'harvest': {
      'unlock': {'garden': 3, 'line': 5},
      'cost': {'line': 5},
      'benefit': {'harvest': 1},
      'title': 'Harvest',
      'text': 'For a price, the garden will be clear.',
      'max_buy': -1,
      'display_message': 'Reap and you shall sow.',
    },
    'plant_pellets2': {
      'unlock': {'pellets': 'Math.ceil((8**n)/4)', 'garden': 1},
      'cost': {'pellets': '8**n'},
      'benefit': {'garden': 1},
      'title': 'Expand the Garden',
      'text': 'Something seems to be missing.',
      'max_buy': 3,
      'display_message': 'How does this not require more space?',
    },
    'unknown': {'unlock': {'unknown': 1}, 'cost': {'unknown': 1}}
  },
  'unknown': {}
};
